### PR TITLE
updates libs

### PR DESCRIPTION
**Pull request by smulesoft**

### CODE REVIEW

**Comment by smulesoft** [comment]
@jstoiko Ok, this is the only one I need for now, let me know how you want to do this. The sooner there is a new release the better.

**Comment by postatum** [comment]
Created an issue for what I described https://github.com/mulesoft/osprey/issues/174

**Comment by smulesoft** [comment]
@postatum Thanks for the review. Will it automatically be released?

**Comment by postatum** [comment]
> @postatum Thanks for the review. Will it automatically be released?

Not sure. @jstoiko can you answer this please?

**Pull request merged**
