### PR TITLE
Console bug: Method popup window is too small for simple APIs

### PR DESCRIPTION
**Pull request by gimballock**
For simple APIs with one or two calls the method popup of the console is so small it is unusable.  To fix change the height to 100% for the html and body tag.

To verify create an Osprey project from a simple RAML file with two API calls.  Then try clicking the "Try It" button from http://hostname:3000/api/console

### CODE REVIEW

**Comment by everyplace** [comment]
This discussion is a bit old, but multiple teams that I care about are getting burned by this at the moment. I've filed the bug as per @dmartinezg's suggestion against the [api-console](https://github.com/mulesoft/api-console/issues/127) project, and hopefully you can advocate for this being resolved. Although this may be on hold because of a newer version of the api console being worked on, fixing this incredibly small problem would help out a lot of people now.

**Comment by blakeembrey** [comment]
@everyplace I'll see about updating the old Osprey version for you. Do you know if the new console resolves the issue for you?

**Comment by everyplace** [comment]
@blakeembrey Is there a way to test the new version of the console?

**Comment by blakeembrey** [comment]
Not within the context of Osprey, it'd have to be from the API console repository. I can go ahead with an update if it's stable to release and see how that works for you too.

**Comment by everyplace** [comment]
I'm more than willing to try and be a guinea pig for the upgrade path.

**Comment by blakeembrey** [comment]
I'm closing old PRs to `0.1.x`. If this issue remains for you and you're still on `0.1.x` of Osprey, please feel free to re-submit the PR and I'll review it ASAP.

**Pull request closed without merging**
