### PR TITLE
Updated datatype-expansion version

### LINKED ISSUE #154: Datatype-expansion version handles AdditionalProperties false
I haven't debugged that in detail and the commit log of the datatype-expansion module is long...

However, in the currently used 0.1.0 version, the setting of "AdditionalProperties" at least was not expanded correctly and thus not handled by the router.

Using the current 0.2.5 works in my environment correctly. I'll submit a PR for this where hopefully all tests succeed. 😄

### PR DESCRIPTION
**Pull request by dploeger**
Fixes #154

### CODE REVIEW

**Comment by dploeger** [comment]
Sure.

**Comment by jstoiko** [comment]
Two more things:
- thing 1: it might be worth considering moving the `expandTypes()` (and `NON_EXPANDABLE_TYPES`) from `lib/server.js` to a separate `lib/raml.js` file, exporting it and then reusing it across the board (in both `lib/server.js` and `test/additional-properties.js`), what do you think?
- thing 2: would you mind changing the `node_js` section of Travis to test against node versions 4, 5, 6, 7, 8. This way it will obvious we're dropping support for v0.1x. We should also get a green build as a result which is always nice.

**Comment by jstoiko** [comment]
oh, and I forgot: don't you think the test should test the Osprey end-functionality rather than the expansion itself?

I.e. spawn/mock a server using that RAML file and test a request/response like it's done here: https://github.com/mulesoft/osprey/blob/master/test/types.js#L134-L149

**Comment by dploeger** [comment]
Probably, but I didn't want to mangle with the code too much. 😄 

I'll do that, but I think, that testing the method like a unit test instead of testing the service like an integration test is better in this case, because we can identify the point of the bug quite well.

**Comment by dploeger** [comment]
Done

**Comment by blai** [comment]
@jstoiko Any updates on this?

**Comment by jstoiko** [comment]
Yes. We need to make a new release with this, #155 (#154), #148 and tentatively #151. I'll try to get around to do this in the next few days.

**Comment by ForsakenHarmony** [comment]
I don't think testing against 5 and 7 is a good idea, they were never LTS and are not supported

**Comment by jstoiko** [comment]
@ForsakenHarmony: right. let's un-Travis those versions.

**Pull request merged**
