### PR TITLE
Basic HTTP Authentication: add support for passport option "passReqToCallback"

### LINKED ISSUE #147: Basic HTTP Authentication: add the support for the passport option "passReqToCallback"
For basic authentication, [Passport-http](https://github.com/jaredhanson/passport-http/blob/master/lib/passport-http/strategies/basic.js) has the option *passReqToCallback* to add *req* as the callback's first parameter.

I'd like to use it in the options defined in Osprey when calling *loadFile*.
Something like that:
```javascript
    osprey.loadFile(raml, {
        security: {
            token_auth: function () {
                return { handler: security.token_auth }
            },
            basic_auth: {
                realm: 'API', // Optional
                passReqToCallback: true,
                validateUser: security.basic_auth
            }
        }
    })
...
```

From what I can see in Osprey's [security handler](https://github.com/mulesoft/osprey/blob/master/lib/security/handler.js) (function *createBasicAuthHandler*) the only supported option is *realm*.

Thanks!

### PR DESCRIPTION
**Pull request by jmesters**
Fixes #147

### CODE REVIEW

**Comment by jstoiko** [comment]
Thanks for this!

Will this work with the version of passport referenced in the package.json file? If not, we should probably consider bumping the version of all passport-related libraries.

Also, would you mind adding the new option to the README (https://github.com/mulesoft/osprey/blob/master/README.md#basic-authentication)?

**Comment by jmesters** [comment]
I haven't changed the package.json file in the fork so it should be correct with the current version.
I've updated the README file although I'm not sure it's the preferred way to add documentation for a new parameter.

**Comment by jstoiko** [comment]
@jmesters: apologies for the late follow-up. wouldn't it make sense to add that option to `digest_auth` as well? [Here](https://github.com/jmesters/osprey/blob/61ea345da25858fc770ccb58cf210590fde0a2aa/lib/security/handler.js#L382).

**Comment by ForsakenHarmony** [comment]
The option doesn't seem to exist for `digest_auth`

**Comment by jstoiko** [comment]
This was released in v0.5.0. Thanks again x1000 @jmesters!

**Comment by jmesters** [comment]
You're welcome, thanks for the version.
I'm not sure I would have time to take a side project but thank you for the invite nonetheless.

**Pull request merged**
